# Generated by Django 5.0.4 on 2024-05-01 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('car', models.CharField(max_length=25)),
                ('driver_license_number', models.CharField(max_length=50)),
                ('driver_license_expiry_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_hired', models.DateField(null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('SUV', 'SUV'), ('TRUCK', 'TRUCK')], default=False, max_length=25)),
                ('Mirrors', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('Seats', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=100)),
                ('Electronics', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('Fuel_level', models.CharField(choices=[('Empty', 'Empty'), ('Almost Empty', 'Almost Empty'), ('1/4', '1/4'), ('1/2', '1/2'), ('Full', 'Full')], max_length=50)),
                ('Damage', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('Medical_kit', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('Body', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('Tires', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=50)),
                ('General_Remarks', models.TextField(blank=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order_assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=30)),
                ('current_location', models.CharField(max_length=100)),
                ('delivery_location', models.CharField(max_length=100)),
                ('customer_order', models.TextField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
