# Generated by Django 5.0.4 on 2024-05-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('TRUCK', 'TRUCK')], max_length=50)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='vehicle_pics')),
                ('license_plate_number', models.CharField(max_length=15)),
            ],
        ),
    ]
