# Generated by Django 5.0.4 on 2024-05-01 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_rename_order_assignments_order_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_assignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
